# support one of Anaconda's Python installers to provide Python3.  we prefer
# Anaconda over Miniconda if both are installed.
if [ -d "${HOME}/anaconda3/bin" ]; then
    export PATH="${HOME}/anaconda3/bin:${PATH}"
elif [ -d "${HOME}/miniconda3/bin" ]; then
    export PATH="${HOME}/miniconda3/bin:${PATH}"
fi

# activate the base environment if we found either version of Anaconda's python.
TEST_CONDA_PATH=`which conda 2>/dev/null`
if [ -n "${TEST_CONDA_PATH}" ]; then
    # bootstrap Anaconda into the environment.
    #
    # NOTE: generated by 'conda init bash'
    #
    __conda_setup="$('/home/gthomsen/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "${__conda_setup}"
    else
        if [ -f "${HOME}/anaconda3/etc/profile.d/conda.sh" ]; then
            . "${HOME}/anaconda3/etc/profile.d/conda.sh"
        else
            export PATH="${HOME}/anaconda3/bin:${PATH}"
        fi
    fi
    unset __conda_setup

    # activate the environment.
    conda activate base
else
    echo "Could not find 'conda' in the PATH!  Anaconda's python installation is not present." >&2
fi

unset TEST_CONDA_PATH
